#!/bin/bash
# @author Ralf Habacker
# @brief lint xmi fils and extract missing dtd elements/attributes from xmllint error messages
#

# fails also on piped failure
#set -euo pipefail

# enable trace
set -x

trap "cat out.log" ERR

# determine root dir
r=$(realpath $0)
r=$(dirname $r)
r=$(dirname $r)

if test "$1" == "--uml2"; then
    stylesheet=$r/doc/xml/uml-2.4.1-umbrello.dtd
    shift
else
    stylesheet=$r/doc/xml/uml-1.4-umbrello.dtd
fi

if test -n "$1"; then
    dir="$1"
else
    dir="$r/models/diagrams/"
fi

find $dir -name '*.xmi' -print | xargs -n 1 xmllint --dtdvalid $stylesheet --noout  2> out.log;  $r/tools/xmllint2dtd out.log

result=$?
exit $result
